trigger:
- main

variables:
  nodeVersion: '18.x'
  functionAppName: 'archit-cicd-function'
  resourceGroupName: 'function-rg'
  location: 'East US'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build the Function App'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '$(nodeVersion)'
        checkLatest: true
    
    - script: |
        echo "Installing dependencies..."
        npm install
      displayName: 'Install Dependencies'
      workingDirectory: '$(System.DefaultWorkingDirectory)/MyFuncApp'
    
    - script: |
        echo "Running linting..."
        npm run lint
      displayName: 'Run Linting'
      workingDirectory: '$(System.DefaultWorkingDirectory)/MyFuncApp'
    
    - script: |
        echo "Running tests..."
        npm test
      displayName: 'Run Tests'
      workingDirectory: '$(System.DefaultWorkingDirectory)/MyFuncApp'
    
    - script: |
        echo "Creating deployment package..."
        cd $(System.DefaultWorkingDirectory)/MyFuncApp
        zip -r function-app.zip . -x "node_modules/*" "*.test.js" "__tests__/*" "coverage/*"
      displayName: 'Create Deployment Package'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/MyFuncApp/function-app.zip'
        artifactName: 'function-app'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: Deploy
    displayName: 'Deploy Function to Azure'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: function-app
      displayName: 'Download Build Artifacts'
    
    - task: AzureCLI@2
      displayName: 'Create Resource Group'
      inputs:
        azureSubscription: 'AzureServiceConnection1'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Creating resource group if it doesn't exist..."
          az group create --name $(resourceGroupName) --location $(location) --output none
          echo "Resource group ready: $(resourceGroupName)"
    
    - task: AzureCLI@2
      displayName: 'Create Storage Account'
      inputs:
        azureSubscription: 'AzureServiceConnection1'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Creating storage account if it doesn't exist..."
          storageAccountName="$(functionAppName)storage$(Build.BuildId)"
          az storage account create \
            --name $storageAccountName \
            --resource-group $(resourceGroupName) \
            --location $(location) \
            --sku Standard_LRS \
            --output none
          echo "Storage account created: $storageAccountName"
    
    - task: AzureCLI@2
      displayName: 'Create Function App'
      inputs:
        azureSubscription: 'AzureServiceConnection1'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Creating Function App if it doesn't exist..."
          storageAccountName="$(functionAppName)storage$(Build.BuildId)"
          
          if ! az functionapp show --name $(functionAppName) --resource-group $(resourceGroupName) --output none 2>/dev/null; then
            echo "Creating Function App..."
            az functionapp create \
              --name $(functionAppName) \
              --resource-group $(resourceGroupName) \
              --consumption-plan-location $(location) \
              --runtime node \
              --runtime-version 18 \
              --functions-version 4 \
              --storage-account $storageAccountName \
              --os-type Linux
            echo "Function App created successfully!"
          else
            echo "Function App already exists!"
          fi
    
    - task: AzureFunctionApp@1
      displayName: 'Deploy Function App'
      inputs:
        azureSubscription: 'AzureServiceConnection1'
        appType: 'functionApp'
        appName: '$(functionAppName)'
        package: '$(Pipeline.Workspace)/function-app/function-app.zip'
        deploymentMethod: 'auto'
    
    - script: |
        echo "##vso[task.setvariable variable=functionUrl]https://$(functionAppName).azurewebsites.net/api/HelloWorld"
        echo "Function deployed successfully!"
        echo "Function URL: https://$(functionAppName).azurewebsites.net/api/HelloWorld"
        echo "Test the function with:"
        echo "curl 'https://$(functionAppName).azurewebsites.net/api/HelloWorld?name=YourName'"
      displayName: 'Set Function URL'
