trigger:
- main

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
        checkLatest: true
    - script: npm install
      displayName: 'Install dependencies'

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: npm test || echo "No tests to run"
      displayName: 'Run Tests'

- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'AzureServiceConnection1'
        appType: functionApp
        appName: 'archit-cicd-function'
        package: '$(System.DefaultWorkingDirectory)'
